all:
  children:
    k3s_local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          # Disable privilege escalation for local k3d environment
          ansible_become: false
