all:
  children:
    k3s_cluster:
      children:
        k3s_masters:
          hosts:
            prod-k3s-master-01:
              ansible_host: "{{ lookup('env', 'PROD_MASTER_HOST') | default('10.0.2.10', true) }}"
              ansible_user: debian
              ansible_ssh_private_key_file: "{{ lookup('env', 'PROD_SSH_KEY') | default('~/.ssh/production_key', true) }}"
              k3s_control_plane: true

        k3s_workers:
          hosts:
            prod-k3s-worker-01:
              ansible_host: "{{ lookup('env', 'PROD_WORKER1_HOST') | default('10.0.2.11', true) }}"
              ansible_user: debian
              ansible_ssh_private_key_file: "{{ lookup('env', 'PROD_SSH_KEY') | default('~/.ssh/production_key', true) }}"

            prod-k3s-worker-02:
              ansible_host: "{{ lookup('env', 'PROD_WORKER2_HOST') | default('10.0.2.12', true) }}"
              ansible_user: debian
              ansible_ssh_private_key_file: "{{ lookup('env', 'PROD_SSH_KEY') | default('~/.ssh/production_key', true) }}"

            prod-k3s-worker-03:
              ansible_host: "{{ lookup('env', 'PROD_WORKER3_HOST') | default('10.0.2.13', true) }}"
              ansible_user: debian
              ansible_ssh_private_key_file: "{{ lookup('env', 'PROD_SSH_KEY') | default('~/.ssh/production_key', true) }}"
